module.exports = {
  TAG_TITLE: 'title',
  TAG_SUBJECT: 'subject',
  TAG_CREATOR: 'creator',
  TAG_LAST_MODIFIED_BY: 'lastModifiedBy',
  TAG_REVISION: 'revision',
  TAG_LAST_PRINTED: 'lastPrinted',
  TAG_CREATED: 'created',
  TAG_MODIFIED: 'modified',
  TAG_TEMPLATE: 'Template',
  TAG_TOTAL_TIME: 'TotalTime',
  TAG_PAGES: 'Pages',
  TAG_WORDS: 'Words',
  TAG_CHARACTERS: 'Characters',
  TAG_APPLICATION: 'Application',
  TAG_DOC_SECURITY: 'DocSecurity',
  TAG_LINES: 'Lines',
  TAG_PARAGRAPHS: 'Paragraphs',
  TAG_SCALE_CROP: 'ScaleCrop',
  TAG_COMPANY: 'Company',
  TAG_LINKS_UP_TO_DATE: 'LinksUpToDate',
  TAG_CHARACTERS_WITH_SPACES: 'CharactersWithSpaces',
  TAG_SHARED_DOC: 'SharedDoc',
  TAG_HYPERLINKS_CHANGED: 'HyperlinksChanged',
  TAG_APP_VERSION: 'AppVersion'
}
